version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: book-nginx-container
    ports:
      - ${NGINX_PORT}:80
      - "443:443"
    volumes:
      - ./logs:/var/log/nginx
      - ./app:/var/www/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./ssl/nginx.key:/etc/nginx/ssl/nginx.key
      - ./ssl/nginx.conf:/etc/nginx/ssl/nginx.csr
    depends_on:
      - php
      - mysql
    networks:
      - book_nginx_php_mysql
    links:
      - redis
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: book-php-container
    restart: always
    ports:
      - ${PHP_PORT}:9000
    volumes:
      - ./app:/var/www/app
      - ./php-www.conf:/usr/local/etc/php-www.conf
    networks:
      - book_nginx_php_mysql
    links:
      - redis

  mysql:
    image: mariadb:11
    container_name: book-mysql-container
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - book_nginx_php_mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: book-phpmyadmin-container
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - book_nginx_php_mysql

  redis:
    container_name: book-redis-container
    image: "redis:alpine"
    command: redis-server
    restart: always
    expose:
      - 6379
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    networks:
      - book_nginx_php_mysql

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    container_name: book-redis-manager
    depends_on:
      - redis
    links:
      - redis
    environment:
      ADMIN_USER: admin
      ADMIN_PASS: admin
      REDIS_1_NAME: MyRedis
      REDIS_1_HOST: redis
    ports:
      - ${PHP_REDIS_ADMIN_PORT}:80
    networks:
      - book_nginx_php_mysql

networks:
  book_nginx_php_mysql:
    external: true

volumes:
  mysql:
  redis-data:
  redis-conf:
