dc:
	symfony console d:d:c
dd:
	symfony console d:d:d --force
mc:
	symfony console make:migration
dm:
	symfony console d:m:m
me:
	symfony console make:entity
fc:
	symfony console make:fixtures
fl:
	symfony console d:f:l
cc:
	symfony console cache:clear

push:
	symfony console d:d:d --force
	symfony console d:d:c
	symfony console d:m:m
	symfony console d:f:l